development:
  adapter: postgresql
  encoding: unicode
  database: austinpetstylist_development
  pool: 5
  username: postgres
  password: postgres
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: austinpetstylist_test
  pool: 5
  username: postgres
  password: postgres
  host: localhost 
